### ISSUE TITLE
Como já criamos outros templates base para laravel, qual destino desse (delete?)?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/laravel-usp-theme#1]

**Comment by girol** [comment]
@thiagogomesverissimo esse aqui não é bem pra Laravel. Tava olhando aqui meu histórico, era pra fazer um tema base como o da incubadora de sites, que tem um template já com a paleta da USP. Provavelmente não vou continuar com esse projeto dadas as circunstâncias atuais, além de não ter nada pronto.

Mas nunca foi tipo, um AdminLTE ou algo do tipo :cat:

**Comment by thiagogomesverissimo** [comment]
ok, por ora eu vou aproveitar para fazer esse tema com as cores da usp no laravel e aproveitar esse projeto. Depois podemos fazer para outro frameworks.

**Comment by girol** [comment]
Tem duas referências:

Site da Pós em Física Aplicada à Medicina e Biologia: http://sites.usp.br/famb/

E o do Departamento de Computação e Matemática de RP: http://dcm.ffclrp.usp.br/

O primeiro, está na incubadora e em Wordpress. Pedi os fontes, eles me falaram pra eu ir no navegador em: `Arquivo -> Salvar Página Como...`

O segundo, tenho os fontes comigo, mas quem desenvolveu foi o Tiago aqui do outro Depto.

**Comment by thiagogomesverissimo** [comment]
De boas, da para escrever um css razoavel com um pouco de engenharia reversa.

**Comment by thiagogomesverissimo** [comment]
Estou preparando o repo para incorporar template USP desenvolvido pelo @marcelomodesto.
