### ISSUE TITLE
Usar getenv() em config/laravel-usp-theme.php em campos básicos

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/laravel-usp-theme#17]

**Comment by masakik** [comment]
'dashboard_url' => getenv('APP_URL'),
    'logout_url' => '/logout' ---> o getenv('APP_URL') estaria embutido no código??

**Comment by masakik** [comment]
Já faria junto com o #18

**Comment by masakik** [comment]
foi aplicado config('app.url') em todos os campos.
