### ISSUE TITLE
Opção can na configuração do menu

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/laravel-usp-theme#18]
Vejo duas possibilidades para tratar o caso de usuário logado.

1 - Fazer como o adminLte-laravel, onde o sistema que vai usar o tema deve criar um Gate para usuário logados, assim na configuração do menu faríamos "can => 'logado'". Código abaixo é uma possível implementação do Gate.

```
        #  Dentro do métdo  boot() em app/Providers/AuthServiceProvider
        Gate::define('logado', function ($user) { 
            if($user){
                return true;            
            }
            else {
                return false;
            }
        });
```

2 - Criar outra opção na configuração do menu, além do can, por exemplo:
```
        [
            'text' => 'Item 3',
            'url'  => '/item3',
            'can'  => 'admin',
            'is_authenticated ' => true
        ],
```

**Comment by masakik** [comment]
Sugestão:
'can'  => '' ou sem a entrada, seria para usuário autenticado (default)
'can' => 'guest' para todos, incluindo usuários não autenticados
'can' => 'admin ou outra coisa' conforme os gates criados

Dessa forma não precisa criar o is_authenticated. E como o padrão é para usuários autenticados ficaria o mínimo de escrita

**Comment by alecostaweb** [comment]
Não mais simples deixar o 'can' comentado no config/laravel-usp-theme.php e a gosto do dev utilizar o gate como quiser?

**Comment by alecostaweb** [comment]
As sugestões são legais, mas vai depender do propósito do sistema e como o dev vai aplicar a regra do negócio

**Comment by masakik** [comment]
a ideia do default é para não ter de criar gate para a situação mais comum. para os demais valores de can, admin por exemplo, seria a regra umplementada pelo desenvolvedor

**Comment by alecostaweb** [comment]
Acho que disse o mesmo rs

**Comment by thiagogomesverissimo** [comment]
Tá perfeito essa solução de deixar uma opção default e o can para que usa o gate.

**Comment by masakik** [comment]
vou implementar isso aqui e mandar o PR.
