### ISSUE TITLE
Que tal uma opção para o logo da unidade?

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/laravel-usp-theme#19]
Como os sistemas são locais, pensei em adicionar ao tema a opção de se adicionar o logo da unidade. O que acham?

**Comment by alecostaweb** [comment]
![pesosas](https://user-images.githubusercontent.com/10613364/59197973-0a2c1980-8b69-11e9-8156-d5fb368ef977.png)

**Comment by masakik** [comment]
É a mesma pergunta da #3.  Acho que é legal

**Comment by alecostaweb** [comment]
Ops, pode fechar então

**Comment by thiagogomesverissimo** [comment]
Seria ótimo! Quer tentar implementar?

**Comment by leandroramos** [comment]
Vou implementar isso, mas estou em dúvida se é melhor colocar instruções para o pessoal gravar a imagem nos assets do tema ou se é melhor outra abordagem, como no banco de dados (mas nesse caso teria que padronizar os sistemas tbm, o que parece difícil).

**Comment by tadeumesquita** [comment]
Será que é indicado salvar a imagem da logo no banco em base64? https://www.base64-image.de/

**Comment by masakik** [comment]
> Vou implementar isso, mas estou em dúvida se é melhor colocar instruções para o pessoal gravar a imagem nos assets do tema ou se é melhor outra abordagem, como no banco de dados (mas nesse caso teria que padronizar os sistemas tbm, o que parece difícil).

Eu acho melhor as instruções para colocar imagem no asset.
