### ISSUE TITLE
Colocar logo da USP no HTML e não no fundo do CSS

### ISSUE THREAD

**Issue by leandroramos** [uspdev/laravel-usp-theme#25]
Para melhorar a semântica e a acessibilidade, é melhor colocar as imagens no HTML com o atributo alt, e não no background do CSS.

**Comment by tadeumesquita** [comment]
Posso fazer essa issue?

**Comment by leandroramos** [comment]
Já fiz, vou mandar PR

**Comment by leandroramos** [comment]
Fiz a PR, @tadeumesquita - se puder revisar, ficarei grato :)

**Comment by tadeumesquita** [comment]
Feito @leandroramos :metal:
