### ISSUE TITLE
Que tal mostrar a versão da aplicação que usa o laravel-usp-theme?

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/laravel-usp-theme#43]
A versão da aplicação poderia ser exibida ou ao lado do nome da aplicação ou no rodapé.
Seria mais uma variável .env.example:
APP_VERSION=1.0.16

Pode-se configurar em config/app.php

```bash
/*
|--------------------------------------------------------------------------
| Application Version
|--------------------------------------------------------------------------
|
| This value is the version of your application. This value is used when
| the framework needs to place the application's version in a notification
| or any other location as required by the application or its packages.
*/
'version' => env('APP_VERSION', '1.0.16'),
``` 

Onde 1.0.16 é o release do projeto uspdev que utiliza o laravel-usp-theme.

Pode ser que o projeto abaixo automatize isso:
https://github.com/antonioribeiro/version

**Comment by masakik** [comment]
Não seria legal que ficasse em um arquivo comitado no repositório, assim a atualização seria automática.
Só não sei onde.

**Comment by alecostaweb** [comment]
Não estamos dizendo a mesma coisa?

**Comment by masakik** [comment]
Ele não deve ficar no .env. Deveria ser app.config.version ou algo assim e ser hard coded.

**Comment by alecostaweb** [comment]
Essa chamada 
```bash
'version' => env('APP_VERSION', '1.0.16'),
```
se existe no .env mostra, se não considera 1.0.16
Não é a mesma coisa que vc disse?

**Comment by masakik** [comment]
Como temos skins talvez isso possa ser implementado no skin

**Comment by masakik** [comment]
Com o uso de skin, não precisamos dessa funcionalidade no skin padrão do uspdev.
