### ISSUE TITLE
csrf-token

### ISSUE THREAD

**Issue by wgnann** [uspdev/laravel-usp-theme#44]
Aparentemente falta definir alguma variável no meta para poder usar no ajax. Do contrário, ele falha por não possuir csrf. Pelo que eu li, um bom lugar seria colocar o meta nos headers do adminlte.

`<meta name="csrf-token" content="{{ csrf_token() }}">`

**Comment by thiagogomesverissimo** [comment]
Adicionado em https://github.com/uspdev/laravel-usp-theme/commit/4663b03536815e1ce653ee67b8a77bc0e3f76910
