### ISSUE TITLE
Comando para publicação das assets não funciona no Windows

### ISSUE THREAD

**Issue by dpicon83** [uspdev/laravel-usp-theme#52]
Comando executado manualmente ou via composer install, após inserido no composer.json, retorna erro. Os arquivos css, js e imagens não são enviados à pasta public/

`php artisan vendor:publish --provider='Uspdev\\UspTheme\\ServiceProvider' --tag=assets --force`
`Unable to locate publishable resources.`

No ambiente de teste, executando apache através do aplicativo Xampp7. 

Versão do PHP: PHP 7.4.6 
Versão do Laravel: 8.10.0

**Comment by thiagogomesverissimo** [comment]
E assim:
`
php artisan vendor:publish --provider='Uspdev/UspTheme/ServiceProvider' --tag=assets --force`

Vai?

**Comment by dpicon83** [comment]
Não vai. Mas acabo de descobrir o que houve, as aspas simples não funcionam. 

Trocando para aspas duplas, funciona normal

php artisan vendor:publish --provider="Uspdev\UspTheme\ServiceProvider" --tag=assets --force
