### ISSUE TITLE
Implementar menu dinâmico

### ISSUE THREAD

**Issue by fgmusp** [uspdev/laravel-usp-theme#58]
baseado em https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#84-menu-configuration-at-runtime
pensado inicialmente para conseguir mostrar um menu de 'anos' exibindo o ano selecionado como label

**Comment by masakik** [comment]
na sexta verificamos que é possivel alterar o conteudo do menu usando config
