### ISSUE TITLE
TypeError: $(...).DataTable is not a function

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/laravel-usp-theme#61]
vendor/laravel-usp-theme/js/script.js:16

`ncaught TypeError: $(...).DataTable is not a function`

Linha 16:
`$('.dataTable, .datatable').DataTable`

**Comment by masakik** [comment]
onde aconteceu isso?

**Comment by thiagogomesverissimo** [comment]
Não lembro.. kkk 
Vou tentar achar o sistema... e posto aqui
