### ISSUE TITLE
Implementar componentes para formularios

### ISSUE THREAD

**Issue by masakik** [uspdev/laravel-usp-theme#86]
haveria componentes para input, select, textarea, etc para melhorar o reaproveitamento e limpar um pouco os códigos.

https://laravel.com/docs/8.x/blade#components

o que acha @thiagogomesverissimo ?

**Comment by thiagogomesverissimo** [comment]
seria bacana... mas vou fechar dado que essa issue tem 3 anos.
Qualque coisa podemos re-abri-lá
